# Generated by Django 4.1.7 on 2023-06-03 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="avatar",
            field=models.ImageField(
                default="default-avatar.png", upload_to="avatars%Y%m%d"
            ),
        ),
    ]
