# Generated by Django 4.1.7 on 2023-06-04 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_alter_post_cover"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="cover",
            field=models.ImageField(blank=True, upload_to="covers/"),
        ),
    ]
